import type { ReactNode } from "react";
import { Link } from "@tanstack/react-router";
import { AlertCircle, Loader2, ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import type { Priority } from "@/lib/types";
import { cn } from "@/lib/utils";

export function PageHeader({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) {
  return (
    <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between animate-rise">
      <div>
        <h1 className="text-2xl font-semibold md:text-3xl">{title}</h1>
        {description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}
      </div>
      {actions && <div className="flex flex-wrap gap-2">{actions}</div>}
    </div>
  );
}

export function Disclaimer({ compact }: { compact?: boolean }) {
  return (
    <div role="note" className="flex gap-3 rounded-lg border border-warning/40 bg-accent/60 p-3 text-sm text-accent-foreground">
      <ShieldAlert className="mt-0.5 size-4 shrink-0" aria-hidden />
      <p>
        <strong>Responsible AI:</strong>{" "}
        {compact
          ? "AI output may contain mistakes. Review before using, and don't enter confidential information. "
          : "AI-generated content may contain mistakes or omissions. Review and verify important information before sending emails, making decisions, or following generated schedules. Do not enter confidential or sensitive information. "}
        {compact && <Link to="/responsible-ai" className="underline underline-offset-2">Learn more</Link>}
      </p>
    </div>
  );
}

export function LoadingState({ label }: { label: string }) {
  return (
    <div role="status" className="flex flex-col items-center justify-center gap-3 py-16 text-muted-foreground">
      <Loader2 className="size-6 animate-spin text-primary" aria-hidden />
      <p className="text-sm">{label}</p>
    </div>
  );
}

export function ErrorState({ message }: { message: string }) {
  return (
    <div role="alert" className="flex gap-3 rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">
      <AlertCircle className="mt-0.5 size-4 shrink-0" aria-hidden />
      <p>{message}</p>
    </div>
  );
}

export function EmptyState({ icon, title, text, action }: { icon: ReactNode; title: string; text: string; action?: ReactNode }) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 rounded-xl border border-dashed bg-muted/40 px-6 py-14 text-center">
      <div className="mb-1 flex size-11 items-center justify-center rounded-full bg-secondary text-secondary-foreground">{icon}</div>
      <p className="font-display font-medium">{title}</p>
      <p className="max-w-sm text-sm text-muted-foreground">{text}</p>
      {action && <div className="mt-3">{action}</div>}
    </div>
  );
}

export function PriorityBadge({ p }: { p: Priority }) {
  return (
    <Badge
      variant="outline"
      className={cn(
        "border-transparent",
        p === "High" && "bg-destructive/10 text-destructive",
        p === "Medium" && "bg-warning/20 text-warning-foreground",
        p === "Low" && "bg-secondary text-secondary-foreground",
      )}
    >
      {p}
    </Badge>
  );
}

export function SourceBadge({ source }: { source: "ai" | "mock" }) {
  return (
    <Badge variant="outline" className="font-normal text-muted-foreground">
      {source === "ai" ? "Generated by AI" : "Demo response"}
    </Badge>
  );
}

export async function copyText(text: string) {
  try {
    await navigator.clipboard.writeText(text);
    toast.success("Copied to clipboard");
  } catch {
    toast.error("Couldn't copy — please select and copy manually.");
  }
}

export function errMsg(e: unknown) {
  return e instanceof Error ? e.message : "Something went wrong. Please try again.";
}
